<?php
//首页
Route::get('/','frontend/index/index')->name('index');
//文章列表
Route::get('/list$','frontend/article/article')->name('article_list');
//分类栏
Route::get('/list/category$','frontend/article/category')->name('ajax_category_list');
//标签栏
Route::get('/list/tag$','frontend/article/tag')->name('ajax_tag_list');
//内容详情
Route::get('/list/:id/detail$','frontend/article/detail')
			->pattern(['id'=>'\d+'])
			->name('detail_list');
//标签详情
Route::get('/list/:id/tag_detail$','frontend/article/tag_detail')
			->pattern(['id'=>'\d+'])
			->name('tag_detail');
//用户详情
Route::get('/list/:id/user_detail$','frontend/article/user_detail')
			->pattern(['id'=>'\d+'])
			->name('user_detail');